server:
  port: 8000
spring:
  application:
    name: web-application
  datasource:
    url: jdbc:h2:mem:webappdb
  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: false
    show-sql: true
