version: "3"
services:
  auth-service:
    image: auth-service:latest
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8004:8004"
  appointment-service:
    image: appointment-service:latest
    build:
      context: ./appointment-service
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8003:8003"
  client-service:
    image: client-service:latest
    build:
      context: ./client-service
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8001:8001"
  report-service:
    image: report-service:latest
    build:
      context: ./report-service
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8006:8006"
  visit-service:
    image: visit-service:latest
    build:
      context: ./visit-service
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8002:8002"
  web-application:
    image: web-application:latest
    build:
      context: ./web-application
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8000:8000"

