server:
  port: 8006
spring:
  application:
    name: report-service
jwt:
  private-key: classpath:private.key
  public-key: classpath:public.key

services:
  client-service: client-service:8001
  visit-service: visit-service:8002
  appointment-service: appointment-service:8003
